### PR TITLE
Only update disassembly and decode panel when visible

### PR DESCRIPTION
**Pull request by learn-more**
This should speed up scrolling in the hex view with the cursor.

I verified that it builds correctly on a non-msvc build in mingw. (Should I test more setups before submitting a PR?)

### CODE REVIEW

**Comment by solemnwarning** [comment]
Don't worry about testing builds on other platforms if it isn't trivial to do - I like to do a bit of testing on each platform for stuff involving UI anyway.

**Comment by solemnwarning** [comment]
Given it a brief bit of testing under Linux and OS X - on Linux (wxGTK, Trinity Desktop Environment) no EVT_SHOW events ever seem to be delivered, not when switching tabs, creating/destroying controls or even minimising/restoring the window. Appears to work fine on Mac.

Not sure if there is a fully reliable way of detecting "is this control visible" in wxWidgets, aside perhaps from deferring updates until the next EVT_PAINT event (although feels a bit hacky). Could perhaps do that, or add something to MainWindow/Tab to flag which tools are visible via the ToolPanel interface. Thoughts?

**Comment by learn-more** [comment]
> Don't worry about testing builds on other platforms if it isn't trivial to do - I like to do a bit of testing on each platform for stuff involving UI anyway.

Great, thanks

> Given it a brief bit of testing under Linux and OS X - on Linux (wxGTK, Trinity Desktop Environment) no EVT_SHOW events ever seem to be delivered, not when switching tabs, creating/destroying controls or even minimising/restoring the window. Appears to work fine on Mac.
> 
> Not sure if there is a fully reliable way of detecting "is this control visible" in wxWidgets, aside perhaps from deferring updates until the next EVT_PAINT event (although feels a bit hacky). Could perhaps do that, or add something to MainWindow/Tab to flag which tools are visible via the ToolPanel interface. Thoughts?

Initially I started by integrating this in the ToolPanel, until I discovered this event.
Considering it does not work as intented, I'll rework it so that it is part of the ToolPanel interface.

**Comment by learn-more** [comment]
The implementation is updated.

**Comment by solemnwarning** [comment]
Okay... almost there!

Works correctly when switching tabs, *but*, if you close the active tab on Linux and Mac, then the new active tab isn't marked as visible and doesn't get updated. Haven't tried debugging on Mac, but on Linux, `GetSelection()`/`GetPage()` and even `GetCurrentPage()` are returning the page being deleted in the `EVT_NOTEBOOK_PAGE_CHANGED` handler, which I'm positive is yet another bug in wxWidgets... woo.

This means `vtools_adjust()` won't be doing the right thing when the active tab is closed either, so will dig a bit more later and see if I can find a workaround.

**Comment by learn-more** [comment]
> Okay... almost there!
> 
> Works correctly when switching tabs, _but_, if you close the active tab on Linux and Mac, then the new active tab isn't marked as visible and doesn't get updated. Haven't tried debugging on Mac, but on Linux, `GetSelection()`/`GetPage()` and even `GetCurrentPage()` are returning the page being deleted in the `EVT_NOTEBOOK_PAGE_CHANGED` handler, which I'm positive is yet another bug in wxWidgets... woo.
> 
> This means `vtools_adjust()` won't be doing the right thing when the active tab is closed either, so will dig a bit more later and see if I can find a workaround.

That is working fine for me on windows, but maybe because we test it different?
I test like this:
* Open Decode and disassembly panel
* Select a byte in the file that is different from the current selection
* Using View->Tool Panels -> Disassembly I disable the Disassembly
* `OnVToolChange` is now called, with GetOldSelection() being `-1` (`wxNOT_FOUND`), and `GetSelection()` being `0` (The last remaining tool panel).

**Comment by solemnwarning** [comment]
> That is working fine for me on windows, but maybe because we test it different?
> I test like this:
> 
> * Open Decode and disassembly panel
> * Select a byte in the file that is different from the current selection
> * Using `View->Tool Panels -> Disassembly` I disable the Disassembly
> * `OnVToolChange` is now called, with GetOldSelection() being `-1` (`wxNOT_FOUND`), and `GetSelection()` being `0` (The last remaining tool panel).

That's the same way I'm testing - works for me on Windows too. On Linux the event has the same data, but the old page hasn't actually been removed from the notebook yet.

**Comment by learn-more** [comment]
> That's the same way I'm testing - works for me on Windows too. On Linux the event has the same data, but the old page hasn't actually been removed from the notebook yet.

The code to remove that thing does not seem like it would be different between windows and linux:

`rehex.exe!REHex::Tab::tool_destroy` calls `wxBookCtrlBase::DeletePage`, which calls `wxNotebook::DoRemovePage` that first calls `wxNotebookBase::DoRemovePage` to actually remove the page, then handles the event generation.....

So following that, it _should_ work the same on linux?
Maybe the wxWidgets version is completely different, and does still have a bug here?
My windows version is on 3.1.3 here.

For reference, here is the call stack from `tool_destroy` to `set_visible`:

```
>	rehex.exe!REHex::ToolPanel::set_visible(bool visible) Line 33	C++
 	rehex.exe!REHex::Tab::OnVToolChange(wxBookCtrlEvent & event) Line 447	C++
 	rehex.exe!wxAppConsoleBase::HandleEvent(wxEvtHandler * handler, void(wxEvtHandler::*)(wxEvent &) func, wxEvent & event) Line 658	C++
 	rehex.exe!wxAppConsoleBase::CallEventHandler(wxEvtHandler * handler, wxEventFunctor & functor, wxEvent & event) Line 669	C++
 	rehex.exe!wxEvtHandler::ProcessEventIfMatchesId(const wxEventTableEntryBase & entry, wxEvtHandler * handler, wxEvent & event) Line 1416	C++
 	rehex.exe!wxEventHashTable::HandleEvent(wxEvent & event, wxEvtHandler * self) Line 1023	C++
 	rehex.exe!wxEvtHandler::TryHereOnly(wxEvent & event) Line 1612	C++
 	rehex.exe!wxEvtHandler::TryBeforeAndHere(wxEvent & event) Line 3912	C++
 	rehex.exe!wxEvtHandler::ProcessEventLocally(wxEvent & event) Line 1545	C++
 	rehex.exe!wxEvtHandler::ProcessEvent(wxEvent & event) Line 1518	C++
 	rehex.exe!wxWindowBase::TryAfter(wxEvent & event) Line 3470	C++
 	rehex.exe!wxEvtHandler::ProcessEvent(wxEvent & event) Line 1531	C++
 	rehex.exe!wxWindowBase::TryAfter(wxEvent & event) Line 3470	C++
 	rehex.exe!wxEvtHandler::ProcessEvent(wxEvent & event) Line 1531	C++
 	rehex.exe!wxNotebookBase::SendPageChangedEvent(int nPageOld, int nPageNew) Line 200	C++
 	rehex.exe!wxNotebook::SetSelection(unsigned __int64 nPage) Line 340	C++
 	rehex.exe!wxNotebook::DoRemovePage(unsigned __int64 nPage) Line 611	C++
 	rehex.exe!wxBookCtrlBase::DeletePage(unsigned __int64 nPage) Line 382	C++
 	rehex.exe!REHex::Tab::tool_destroy(const std::string & name) Line 253	C++
```

**Comment by solemnwarning** [comment]
> `rehex.exe!REHex::Tab::tool_destroy` calls `wxBookCtrlBase::DeletePage`, which calls `wxNotebook::DoRemovePage` that first calls `wxNotebookBase::DoRemovePage` to actually remove the page, then handles the event generation.....

The Windows wxNotebook implementation works that way, but the GTK and Mac implementations each behave differently (and even between versions!):

=== Add page to empty wxNotebook using wxNotebook->AddPage(x, y, false)

Linux/3.0.4: Both events raised, GetOldSelection() returns -1, GetSelection() returns 0
Linux/3.1.4: Neither event raised
Mac/3.0.4: Neither event raised
Mac/3.1.4: Neither event raised
Windows/3.0.5: Neither event raised
Windows/3.1.4: Neither event raised

=== Add page to empty wxNotebook using wxNotebook->AddPage(x, y, true)

Linux/3.0.4: Both events raised, GetOldSelection() returns -1, GetSelection() returns 0
Linux/3.1.4: Neither event raised
Mac/3.0.4: Neither event raised
Mac/3.1.4: Both events raised, GetOldSelection() returns -1, GetSelection() returns 0
Windows/3.0.5: Both events raised, GetOldSelection() returns -1, GetSelection() returns 0
Windows/3.1.4: Both events raised, GetOldSelection() returns -1, GetSelection() returns 0

=== Remove page 1/2 (currently selected) using wxNotebook->DeletePage()

Linux/3.0.4: Both events raised, GetOldSelection() returns -1, GetSelection() returns 0, BUT page 0 is still the deleted page during the handler
Linux/3.1.4: Both events raised, GetOldSelection() returns -1, GetSelection() returns 0, BUT page 0 is still the deleted page during the handler
Mac/3.0.4: Neither event raised
Mac/3.1.4: Neither event raised
Windows/3.0.5: Both events raised, GetOldSelection() returns -1, GetSelection() returns 0
Windows/3.1.4: Both events raised, GetOldSelection() returns -1, GetSelection() returns 0

=== Remove page 2/2 (currently selected) using wxNotebook->DeletePage()

Linux/3.0.4: Both events raised, GetOldSelection() returns -1, GetSelection() returns 0
Linux/3.1.4: Both events raised, GetOldSelection() returns -1, GetSelection() returns 0
Mac/3.0.4: Neither event raised
Mac/3.1.4: Neither event raised
Windows/3.0.5: Both events raised, GetOldSelection() returns -1, GetSelection() returns 0
Windows/3.1.4: Both events raised, GetOldSelection() returns -1, GetSelection() returns 0

I'm going to raise a bug with the wxWidgets developers to clarify exactly how this should behave and then go ahead and add a workaround for Linux/Mac before merging this PR.

Thanks for your efforts!

**Pull request merged**
