### PR TITLE
Lua integration

### PR DESCRIPTION
**Pull request by learn-more**
First steps towards #4 

Please ignore the dirty commit history and all commented out crap,
this is just showcasing one possible approach.

Most of the lua integration parts are in `plugin/luaenvironment.cpp` and `plugin/luaenvironment.hpp`,
The rest is in `PluginInstance` in `plugin/PluginInstance.cpp`

### CODE REVIEW

**Comment by solemnwarning** [comment]
I think I'm almost done with implementing inline disassembly regions, so might start looking at this properly in the near future. Mind if I ask what led you to use Sol over the official Lua runtime API? Some of Sol's features look nice to me at a glance, but I haven't used either in anger yet.

I was planning on exposing pretty much all C++ API functionality to Lua in the first release, meaning plugins could add their own tool panels, data types with custom processing/rendering and basically anything else... but since I'm *still* having to refactor when adding features (see the disasm-region branch), I'm thinking of keeping it much more limited for now.

**Comment by learn-more** [comment]
> I think I'm almost done with implementing inline disassembly regions, so might start looking at this properly in the near future. Mind if I ask what led you to use Sol over the official Lua runtime API? Some of Sol's features look nice to me at a glance, but I haven't used either in anger yet.
> 
> I was planning on exposing pretty much all C++ API functionality to Lua in the first release, meaning plugins could add their own tool panels, data types with custom processing/rendering and basically anything else... but since I'm _still_ having to refactor when adding features (see the disasm-region branch), I'm thinking of keeping it much more limited for now.

The raw lua api is pretty simple in design, but quite some work to nicely integrate, especially with c++
Sol is simply a wrapper around this, making things like ownership, and order of operations (lua api behaves like a stack) a no-brainer.

In my opinion, the only reason to work with the raw lua api is out of academic interest, or when writing a wrapper like sol.

**Comment by solemnwarning** [comment]
I've done a little poking around, Sol isn't really suitable due to depending on cutting edge C++ compilers (I don't want to force that on users) - even older versions won't build on CentOS 7. Some other standalone binding (e.g. LuaBridge) look promising, but then maybe wxLua would be best since it gives us a wxWidgets binding too... except my initial attempts at *compiling* the sodding thing tonight hasn't gotten anywhere.

I want plugins to at least be able to use message boxes and bind to events (rehex-generated ones primarily), ideally they should have access to the entire wxWidgets API (without us having to wrap it all).

**Comment by solemnwarning** [comment]
I think the implementation in the wxlua-prototype branch is getting pretty close to being production-ready (pending more testing), how does it look to you? Any obvious flaws or capabilities I've missed?

**Comment by solemnwarning** [comment]
Getting ready to release with the current Lua implementation, thanks for exploring this.

**Pull request closed without merging**
