### PR TITLE
Build with Botan 3

### PR DESCRIPTION
**Pull request by andreasstieger**
Botan 2 is EOL EOY 2024

### CODE REVIEW

**Comment by solemnwarning** [comment]
Mainstream Linux distros are still using botan2, and I'm not prepared to raise the minimum C++ version to C++20 yet (hence why the versions can be overridden on platforms where needed).

Where are you building this?

**Comment by andreasstieger** [comment]
Actually distros are moving to Botan 3, and this is a bit of a chicken / egg problem. This is for openSUSE, be briefly looked at offering a transitional package but it looks like we can move the whole distro to Botan 3 right away.

I did not see the option to override, that works better than getting this patch upstream. Works for me now, closing.

**Comment by solemnwarning** [comment]
FYI I've updated the Makefile to detect whether Botan 3.x or 2.x is installed to handle the transition.

**Comment by andreasstieger** [comment]
77fe9c22460caf350c9015e8e3292ff97e3493b0 thanks

**Pull request closed without merging**
