### PR TITLE
Save the size of the main window and the tool splitter

### PR DESCRIPTION
**Pull request by learn-more**

### CODE REVIEW

**Comment by solemnwarning** [comment]
Changes look good, but on Linux (at least) the size of the tool panel glitches out in different ways depending how wide it was set when the view was saved... the sizing code is pretty finnicky and wants rethinking anyway - a common complains is the tool panel being resized unnecessarily when switching tools and making the user lose their place in the file.

**Comment by learn-more** [comment]
Should this remain open until that is fixed?
Or should that be fixed in this PR?

**Comment by solemnwarning** [comment]
I'm not planning on looking at it right this minute (looking at some other features first), if you've got convenient access to Linux/Mac boxes for testing I'd be happy for you to look at refactoring the sizing stuff :)

**Comment by solemnwarning** [comment]
Merged to master in c4717cf50076ce4629ee067a263c429dd46b15d0.

**Pull request closed without merging**
