### PR TITLE
Add page up/ page down handling in documentctrl

### PR DESCRIPTION
**Pull request by learn-more**

### CODE REVIEW

**Comment by solemnwarning** [comment]
Sorry for taking so long to respond to this PR.

I don't really like the way the cursor is adjusted in this, but I can't think of an (easy) way to do it better - the bytes_per_line actual in different data regions may differ when nested comments are in use, and the number of lines of *data* on the screen will differ depending on number of/size of comments too, so the amount the cursor moves in the file won't necessarily reflect the amount the file has been scrolled.

Perhaps the right way for this to behave is to scroll the file up/down, then clamp the cursor to the first/last byte on the screen (assuming there are any)? Can't think of any other applications that deal with scrolling the same sort of control to look at for comparison/inspiration, do you know any?

Thanks

**Comment by learn-more** [comment]
> Sorry for taking so long to respond to this PR.
> 
> I don't really like the way the cursor is adjusted in this, but I can't think of an (easy) way to do it better - the bytes_per_line actual in different data regions may differ when nested comments are in use, and the number of lines of _data_ on the screen will differ depending on number of/size of comments too, so the amount the cursor moves in the file won't necessarily reflect the amount the file has been scrolled.
> 
> Perhaps the right way for this to behave is to scroll the file up/down, then clamp the cursor to the first/last byte on the screen (assuming there are any)? Can't think of any other applications that deal with scrolling the same sort of control to look at for comparison/inspiration, do you know any?
> 
> Thanks

No, the comments inline with the data make this application unique.

However, when testing this it seems to work as expected.
Do you have an example that behaves wrong?

**Comment by solemnwarning** [comment]
I hadn't actually tested this and was just going from reviewing the code, and I misinterpreted what part of it would do - I was expecting the `scroll_yoff` set in `OnChar()` to take precedence over the cursor position set by `_set_cursor_position()`, but the scroll position gets replaced by `_set_cursor_position()` if the cursor falls outside of the visible area, so when comments are scrolled over the scrollbar will jump further to catch up with the cursor instead. Still not sure if this is the best behaviour, but thats subjective really.

As for nested comments, when you have something contrived to show the issue badly like this:

comments

...then the orange region has 22 bytes per line, while the purple one is only 18 bytes per line. Place the cursor in the purple area and hit page up, and it doesn't scroll up a full screen's worth, then press page down and it jumps further than it did on the way up.

Maybe I'm nitpicking too much over something minor. What do you think?

**Comment by learn-more** [comment]
> I hadn't actually tested this and was just going from reviewing the code, and I misinterpreted what part of it would do - I was expecting the `scroll_yoff` set in `OnChar()` to take precedence over the cursor position set by `_set_cursor_position()`, but the scroll position gets replaced by `_set_cursor_position()` if the cursor falls outside of the visible area, so when comments are scrolled over the scrollbar will jump further to catch up with the cursor instead. Still not sure if this is the best behaviour, but thats subjective really.

It is subjective, but ultimately up to you to decide if you want this behavior or prefer something else.


> As for nested comments, when you have something contrived to show the issue badly like this:
> 
> comments
> 
> ...then the orange region has 22 bytes per line, while the purple one is only 18 bytes per line. Place the cursor in the purple area and hit page up, and it doesn't scroll up a full screen's worth, then press page down and it jumps further than it did on the way up.
> 
> Maybe I'm nitpicking too much over something minor. What do you think?

I had indeed not considered a case like this, I'll try if I can make it work in a case like this.
(I hardly ever use the comments, and I never use the nested comments)

**Comment by solemnwarning** [comment]
Can you give the pg_updown branch a quick look/test and tell me if it seems okay to you?

Thanks

**Comment by learn-more** [comment]
> Can you give the pg_updown branch a quick look/test and tell me if it seems okay to you?
> 
> Thanks

Following commits like c11b6a6513ae608ac0052cfe6a59085af6d52188 ?
I'll give it a go, but will probably be in the weekend or later in the next week.

**Comment by solemnwarning** [comment]
Yeah, I rebased your change and came up with a way around the issue discussed earlier. Just wanted your opinion before I merge the changes in.

**Comment by learn-more** [comment]
In my testing when pressing page down on your branch the cursor would not be on the last line, but the line before,
and the last line would also be the 'next' first line.

**Comment by solemnwarning** [comment]
I think that is caused by the window not quite being tall enough to count that last line as fully visible - the cursor being on the second-to-last line should also be what happens if you scroll down with the arrow keys.

**Comment by learn-more** [comment]
> I think that is caused by the window not quite being tall enough to count that last line as fully visible - the cursor being on the second-to-last line should also be what happens if you scroll down with the arrow keys.

indeed it is, so in that case it's intentional and it works as expected 👍

**Comment by solemnwarning** [comment]
Merged!

**Comment by learn-more** [comment]
> Merged!

Thanks!

**Pull request closed without merging**
